name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  python-security:
    uses: project-unisonOS/.github/.github/workflows/reusable-python-security.yml@b8262adfe3ac737ef9fc2e02c337f3983c83c773
    with:
      python-version: "3.11"
      working-directory: "."
