name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  python-security:
    uses: project-unisonOS/.github/.github/workflows/reusable-python-security.yml@34782dbf72d4a61e2ff8d6b860e862ca095667c5
    with:
      python-version: "3.11"
      working-directory: "."
