name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  python-security:
    uses: project-unisonOS/.github/.github/workflows/reusable-python-security.yml@955fd5c8924b1c2b1324453416afc8b6911ff235
    with:
      python-version: "3.11"
      working-directory: "."
